import Head from 'next/head';
import Image from 'next/image';
import Header from './components/Header';
import ProfilePortrait from './components/ProfilePortrait';
import RoleTitle from './components/RoleTitle';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header/>
      </header>

      <main>
      
        <div className='pageTop'>
          <div className={'pageTopContainer'}>
            <RoleTitle />
            <ProfilePortrait />
          </div>
        </div>

        <div className={'pageDividerBackground'}>
          <img className={'pageDivider'} src={'/pageDivider.svg'} />
        </div>
      
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
